{"id":619908,"title":"76｜再回首：“异常处理”单元小结","content":"<p>你好，我是尹会生。</p><p>这一章，我给你介绍了Python异常产生的原因及处理办法。异常是程序运行在某个不受控制的场景时产生的执行结果。这些场景中，有一些是可以被程序员提前预料到的，像数据输入、网络通信超时等场景，都属于这种预期的错误场景。</p><p>对这些预期的错误场景，我们可以在编写程序的主要逻辑时，把异常处理程序编写好，就可以让程序在出现这些预期场景时，告知用户该怎么办，而不是报告程序内部预知的错误提示信息。这也是编写异常处理程序最大的价值。</p><p>但是使用异常处理也要适度，不然异常处理很容易导致程序主要逻辑不清晰，异常提示太宽泛等问题。那么这一讲，我就来为你总结三条异常处理的最佳实践，希望能帮你快速掌握异常处理程序的编写。</p><h3>明确告知异常情景，而不是改变主要逻辑</h3><p>程序输入引发的异常，往往是可以修复的。在这种情况下，开发者一般可以采取两种修复策略：一种是进行数据类型转换，让程序在错误的假设下继续运行；另一种是明确告知程序的调用者，输入的位置出了问题，你需要停下来检查抛出异常的位置。我的建议是采取后面一种策略。</p><p>因为输入数据类型错误，可能并非导致程序出错的唯一原因。因为程序中的函数、对象等复杂数据类型之间，也会传递数据，而在函数返回等过程中，很有可能因为数据类型的副作用，导致程序出现意料之外的执行结果。因此，停下来报错，要比让程序“磕磕绊绊”地执行下来，更能保证数据的正确性。</p>","comments":[{"had_liked":false,"id":393183,"user_name":"8000tank","can_delete":false,"product_type":"c3","uid":3838010,"ip_address":"北京","ucode":"C5DC98A0EB57CE","user_header":"","comment_is_top":false,"comment_ctime":1723083141,"is_pvip":false,"replies":[{"id":143108,"content":"我跳出答案重写一个打开文件的代码，供你参考\n# 定义文件对象 f，并初始化为 None\nf = None\n\ntry:\n    # 打开文件，并将文件对象赋值给 f\n    f = open(&#39;example.txt&#39;, &#39;r&#39;)\n    \n    # 在此进行文件读取操作\n    content = f.read()\n    print(content)\n\nexcept FileNotFoundError as e:\n    # 处理文件未找到异常\n    print(f&quot;Error: {e}&quot;)\n\nexcept IOError as e:\n    # 处理其他输入输出异常\n    print(f&quot;IOError: {e}&quot;)\n\nfinally:\n    # 确保文件对象 f 被关闭\n    if f is not None:\n        f.close()\n        print(&quot;File closed successfully.&quot;)\n\n代码说明：\n定义文件对象 f：\n\nf 被初始化为 None，确保即使在 try 块中没有成功打开文件，也不会出现未定义的问题。\ntry 块：\n\n尝试打开文件并将文件对象赋值给 f。\n如果文件打开成功，可以在这里进行读取操作。比如，使用 f.read() 读取文件内容。\nexcept 块：\n\n捕捉可能出现的异常，如文件未找到（FileNotFoundError）或其他输入输出异常（IOError），并输出相应的错误信息。\nfinally 块：\n\n不论 try 块中是否发生异常，finally 块都会执行。这里用来确保文件被正确关闭。\n通过检查 f 是否为 None，确保只有在文件成功打开后才调用 f.close()。如果 f 为 None，说明文件未成功打开，此时调用 f.close() 不会引发错误。","user_name":"作者回复","user_name_real":"编辑","uid":1056235,"ctime":1726220349,"ip_address":"广东","comment_id":393183,"utype":1}],"discussion_count":1,"race_medal":0,"score":2,"product_id":100310001,"comment_content":"老师，73讲的答案不对吧？finally代码块的“f.close()”会报错误 NameError: name &#39;f&#39; is not defined。\ntry代码块中的f，应该是一个局部变量，在其他块中 无法访问的。","like_count":0,"discussions":[{"author":{"id":1056235,"avatar":"https://static001.geekbang.org/account/avatar/00/10/1d/eb/b2123759.jpg","nickname":"尹会生","note":"","ucode":"D1093DBD093617","race_medal":0,"user_type":2,"is_pvip":false},"reply_author":{"id":0,"avatar":"","nickname":"","note":"","ucode":"","race_medal":0,"user_type":1,"is_pvip":false},"discussion":{"id":651104,"discussion_content":"我跳出答案重写一个打开文件的代码，供你参考\n# 定义文件对象 f，并初始化为 None\nf = None\n\ntry:\n    # 打开文件，并将文件对象赋值给 f\n    f = open(&#39;example.txt&#39;, &#39;r&#39;)\n    \n    # 在此进行文件读取操作\n    content = f.read()\n    print(content)\n\nexcept FileNotFoundError as e:\n    # 处理文件未找到异常\n    print(f&#34;Error: {e}&#34;)\n\nexcept IOError as e:\n    # 处理其他输入输出异常\n    print(f&#34;IOError: {e}&#34;)\n\nfinally:\n    # 确保文件对象 f 被关闭\n    if f is not None:\n        f.close()\n        print(&#34;File closed successfully.&#34;)\n\n代码说明：\n定义文件对象 f：\n\nf 被初始化为 None，确保即使在 try 块中没有成功打开文件，也不会出现未定义的问题。\ntry 块：\n\n尝试打开文件并将文件对象赋值给 f。\n如果文件打开成功，可以在这里进行读取操作。比如，使用 f.read() 读取文件内容。\nexcept 块：\n\n捕捉可能出现的异常，如文件未找到（FileNotFoundError）或其他输入输出异常（IOError），并输出相应的错误信息。\nfinally 块：\n\n不论 try 块中是否发生异常，finally 块都会执行。这里用来确保文件被正确关闭。\n通过检查 f 是否为 None，确保只有在文件成功打开后才调用 f.close()。如果 f 为 None，说明文件未成功打开，此时调用 f.close() 不会引发错误。","likes_number":0,"is_delete":false,"is_hidden":false,"ctime":1726220349,"is_liked":false,"can_delete":false,"is_complain":false,"is_top":true,"parent_id":0,"ip_address":"广东","group_id":0},"score":2,"extra":"{\"reply\":true,\"user_type\":2,\"source\":0}","child_discussion_number":0,"child_discussions":[]}]},{"had_liked":false,"id":369320,"user_name":"yanyu-xin","can_delete":false,"product_type":"c3","uid":1899757,"ip_address":"广东","ucode":"3AA389F9E4C236","user_header":"","comment_is_top":false,"comment_ctime":1677405549,"is_pvip":false,"replies":null,"discussion_count":0,"race_medal":0,"score":2,"product_id":100310001,"comment_content":"# 通过func_timeout装饰器来解决函数执行超时\n\nfrom func_timeout import func_set_timeout\nimport func_timeout\n\n@func_set_timeout(3)#设定函数超执行时间_\ndef task():\n    print(&#39;下载资源文件&#39;) \n    pass # Python 下载网络资源模块\n    time.sleep(5)\n    return &#39;执行成功_未超时&#39;\n\nif __name__ == &#39;__main__&#39;:\n    try:\n        print(task())\n       #若调用函数超时自动走异常(可在异常中写超时逻辑处理)\n    except func_timeout.exceptions.FunctionTimedOut:\n        print(&#39;下载资源超时&#39;)","like_count":1},{"had_liked":false,"id":385089,"user_name":"Geek_631607","can_delete":false,"product_type":"c3","uid":3789991,"ip_address":"广东","ucode":"EAF874838F0BE4","user_header":"","comment_is_top":false,"comment_ctime":1702027364,"is_pvip":false,"replies":null,"discussion_count":0,"race_medal":0,"score":2,"product_id":100310001,"comment_content":"import requests\nfrom requests.exceptions import Timeout\n\ndef download_resource(url):\n    try:\n        hds = {&quot;User-Agent&quot;: &quot;Mozilla&#47;5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit&#47;537.36 (KHTML, like Gecko) Chrome&#47;119.0.0.0 Safari&#47;537.36&quot;}\n        response = requests.get(url, timeout=5, headers=hds)\n        return response.content\n    except Timeout:\n        # 这里可以抛出自定义异常，或者返回特定的错误信息\n        raise Exception(&#39;连接超时，请检查你的网络连接或稍后再试&#39;)\n    \n\nprint(download_resource(&quot;https:&#47;&#47;www.xxx.com&quot;))","like_count":0},{"had_liked":false,"id":384914,"user_name":"760418","can_delete":false,"product_type":"c3","uid":3768167,"ip_address":"上海","ucode":"C160176FE97575","user_header":"","comment_is_top":false,"comment_ctime":1701780833,"is_pvip":false,"replies":null,"discussion_count":0,"race_medal":0,"score":2,"product_id":100310001,"comment_content":"BaseException\n ├── BaseExceptionGroup\n ├── GeneratorExit\n ├── KeyboardInterrupt\n ├── SystemExit\n └── Exception\n      ├── ArithmeticError\n      │    ├── FloatingPointError\n      │    ├── OverflowError\n      │    └── ZeroDivisionError\n      ├── AssertionError\n      ├── AttributeError\n      ├── BufferError\n      ├── EOFError\n      ├── ExceptionGroup [BaseExceptionGroup]\n      ├── ImportError\n      │    └── ModuleNotFoundError\n      ├── LookupError\n      │    ├── IndexError\n      │    └── KeyError\n      ├── MemoryError\n      ├── NameError\n      │    └── UnboundLocalError\n      ├── OSError\n      │    ├── BlockingIOError\n      │    ├── ChildProcessError\n      │    ├── ConnectionError\n      │    │    ├── BrokenPipeError\n      │    │    ├── ConnectionAbortedError\n      │    │    ├── ConnectionRefusedError\n      │    │    └── ConnectionResetError\n      │    ├── FileExistsError\n      │    ├── FileNotFoundError\n      │    ├── InterruptedError\n      │    ├── IsADirectoryError\n      │    ├── NotADirectoryError\n      │    ├── PermissionError\n      │    ├── ProcessLookupError\n      │    └── TimeoutError\n      ├── ReferenceError\n      ├── RuntimeError\n      │    ├── NotImplementedError\n      │    └── RecursionError\n      ├── StopAsyncIteration\n      ├── StopIteration\n      ├── SyntaxError\n      │    └── IndentationError\n      │         └── TabError\n      ├── SystemError\n      ├── TypeError","like_count":0},{"had_liked":false,"id":379410,"user_name":"Geek_Mike","can_delete":false,"product_type":"c3","uid":3196376,"ip_address":"云南","ucode":"CFA942192C3B74","user_header":"https://static001.geekbang.org/account/avatar/00/30/c5/d8/c5509b9c.jpg","comment_is_top":false,"comment_ctime":1691914952,"is_pvip":false,"replies":null,"discussion_count":0,"race_medal":0,"score":2,"product_id":100310001,"comment_content":"import requests\n\ndef connect_expection(url):\n    try:\n        respond = requests.get(url, timeout=3)\n    \n    except requests.exceptions.Timeout:\n        print(&#39;连接超时,请重试,或检查是否有访问权限&#39;)\n\nconnect_expection(&#39;http:&#47;&#47;facebook.com&#39;)","like_count":0}]}